language: node_js
node_js:
- stable
npm: true
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  directories:
  - node_modules
script:
- npm run heroku-prebuild
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: FjHzEWNOmwx6jDymTrrFU4MEBytMjXTA3Qb5EM+dqIuPDtKi83ZyjrqVChs7YS2HQ3yCtvYgYz6/8ukQKmUqGQseUXHuFfzDWNpIczAS6vAeLi0JOqU/uVFUrg7pbOH/hfM9juIyF3RYB1BEkOnT3o3H9r+CGPpLZAMZ+HhPioj9c3agAEmY0P+2yGnda9OV9C435tcuLdfMk397UmdLDV3cRYQGf7kYyw77BGY3ZtAq+MnipMZTEUfjEJnyhG2RyY95YhYafH7xqGYvNMEGN21d5owboRxUckjJkntprXuqrlVgkuZST7KlrQ27Ay+2BSeb/YVUJv+IQx/2305xjfUPUjEDu9Qcz8P4CNNifJ4wj8bUOgbgPbVKGJuDOxZ2XntJ4NJeR6J5ugv/+3ynN7wnKQnZw9tpPkBT8wCYgHmxRtnV62OHO5UpdSckXHLIIn9dtl+lqHynSIGMN1yVhX0efPRFEN52SHpKKYuZ1u+YAdDLOpwKWEsqGyCPEu0YfT9C6trvt556Z8quRv42m7W3eXMtUL8RpND40q8+t3VXhgSTY/Dg1U0L+oMbXK7hmkaUpcK/6t193hDRx5f5HxEVrXXGj+mlt8vZqGl0UzlydINSKBogDhyVBDyi1VC4Ig+FouKe6Bjv+VlUJsy2CIGyPd8BK/4kggPXyn04p7k=
  app: nextfantasyv2
  on:
    repo: andydurette/nextfantasyv2
    branch: master
